// <auto-generated />
using System;
using Microservice.Customer.Address.Api.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microservice.Customer.Address.Api.Migrations
{
    [DbContext(typeof(CustomerAddressDbContext))]
    [Migration("20240507134744_create-populate-tables")]
    partial class createpopulatetables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Customer.Address.Api.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MSOS_Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "England"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Scotland"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wales"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Northern Ireland"
                        });
                });

            modelBuilder.Entity("Microservice.Customer.Address.Api.Domain.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CountryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("County")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TownCity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("MSOS_CustomerAddress");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f65b6b3-031f-4c63-8d56-c8730b0a579b"),
                            AddressLine1 = "23 Long Shank Road",
                            AddressLine2 = "Bordly",
                            AddressLine3 = "Lower Horton",
                            CountryId = 1,
                            County = "West Yorkshire",
                            Created = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8349),
                            CustomerId = new Guid("aa1dc96f-3be5-41cd-8a1b-207284af3fdd"),
                            LastUpdated = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8392),
                            Postcode = "HD6 TRF",
                            TownCity = "Horton"
                        },
                        new
                        {
                            Id = new Guid("a0c1a0ad-1d59-4951-a6cd-2d26951465fd"),
                            AddressLine1 = "9 Short Eared Owl Lane",
                            AddressLine2 = "Coorly",
                            AddressLine3 = "",
                            CountryId = 2,
                            County = "Stirlingshire",
                            Created = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8424),
                            CustomerId = new Guid("af95fb7e-8d97-4892-8da3-5e6e51c54044"),
                            LastUpdated = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8426),
                            Postcode = "ST4 VFR",
                            TownCity = "Stirling"
                        },
                        new
                        {
                            Id = new Guid("86193bba-ab21-49d7-9686-05e1c67df6b3"),
                            AddressLine1 = "1 Sparrow Road",
                            AddressLine2 = "Halthorpe",
                            AddressLine3 = "",
                            CountryId = 3,
                            County = "West Glamorgan",
                            Created = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8438),
                            CustomerId = new Guid("55b431ff-693e-4664-8f65-cfd8d0b14b1b"),
                            LastUpdated = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8439),
                            Postcode = "SW4 NVD",
                            TownCity = "Swansea"
                        },
                        new
                        {
                            Id = new Guid("62aba6d4-5e5c-4566-8d46-2503ee78145a"),
                            AddressLine1 = "3 Osprey Street",
                            AddressLine2 = "Mineton",
                            AddressLine3 = "Manely",
                            CountryId = 4,
                            County = "County Antrim",
                            Created = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8443),
                            CustomerId = new Guid("2385de72-2302-4ced-866a-fa199116ca6e"),
                            LastUpdated = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8444),
                            Postcode = "BF2 PLD",
                            TownCity = "Belfast"
                        },
                        new
                        {
                            Id = new Guid("d0718d52-b5bc-4861-894b-a8f25b0ec1fb"),
                            AddressLine1 = "66 Seagull Way",
                            AddressLine2 = "Limestone",
                            AddressLine3 = "",
                            CountryId = 1,
                            County = "Northamptonshire",
                            Created = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8448),
                            CustomerId = new Guid("47417642-87d9-4047-ae13-4c721d99ab48"),
                            LastUpdated = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8450),
                            Postcode = "PE7 8TY",
                            TownCity = "Oundle"
                        },
                        new
                        {
                            Id = new Guid("e3c4e1f9-8ba9-4cc3-ad0a-69528bb1d0f4"),
                            AddressLine1 = "4 Buzzard Lane",
                            AddressLine2 = "Needleton",
                            AddressLine3 = "Harlslon",
                            CountryId = 2,
                            County = "Aberdeenshire",
                            Created = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8457),
                            CustomerId = new Guid("ff4d5a80-81e3-42e3-8052-92cf5c51e797"),
                            LastUpdated = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8458),
                            Postcode = "AB3 DER",
                            TownCity = "Aberdeen"
                        },
                        new
                        {
                            Id = new Guid("0a077be6-59a1-4768-9c38-722caba15c3f"),
                            AddressLine1 = "15 Avocet Road",
                            AddressLine2 = "Frodingly",
                            AddressLine3 = "",
                            CountryId = 3,
                            County = "South Glamorgan",
                            Created = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8461),
                            CustomerId = new Guid("5ff79dfe-c1fa-4dd9-996f-bc96649d6dfc"),
                            LastUpdated = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8463),
                            Postcode = "CF4 DET",
                            TownCity = "Cardiff"
                        },
                        new
                        {
                            Id = new Guid("335565df-cadf-457a-b15e-f6d2f564fef5"),
                            AddressLine1 = "18 Curlew Street",
                            AddressLine2 = "Bardslow",
                            AddressLine3 = "",
                            CountryId = 4,
                            County = "County Londonderry",
                            Created = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8466),
                            CustomerId = new Guid("ae55b0d1-ba02-41e1-9efa-9b4d4ac15eec"),
                            LastUpdated = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8468),
                            Postcode = "DR4 GTY",
                            TownCity = "Derry"
                        },
                        new
                        {
                            Id = new Guid("a3c18b53-aabd-4ce8-bac9-1e3458356a32"),
                            AddressLine1 = "21 Golden Eagle Way",
                            AddressLine2 = "Plorton",
                            AddressLine3 = "Riddleworth",
                            CountryId = 1,
                            County = "West Yorkshire",
                            Created = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8471),
                            CustomerId = new Guid("c95ba8ff-06a1-49d0-bc45-83f89b3ce820"),
                            LastUpdated = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8472),
                            Postcode = "LS3 VFR",
                            TownCity = "Leeds"
                        },
                        new
                        {
                            Id = new Guid("e6484ab8-801e-4270-8825-359610e83365"),
                            AddressLine1 = "33 Blackbird Lane",
                            AddressLine2 = "Reaverson",
                            AddressLine3 = "",
                            CountryId = 1,
                            County = "Durham",
                            Created = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8477),
                            CustomerId = new Guid("f07e88ac-53b2-4def-af07-957cbb18523c"),
                            LastUpdated = new DateTime(2024, 5, 7, 14, 47, 43, 71, DateTimeKind.Local).AddTicks(8478),
                            Postcode = "PL3 ABF",
                            TownCity = "Easington"
                        });
                });

            modelBuilder.Entity("Microservice.Customer.Address.Api.Domain.CustomerAddress", b =>
                {
                    b.HasOne("Microservice.Customer.Address.Api.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
