version: '3.4'

services:
  microservice.customer.address.api:
    container_name: microservice.customer.address.api
    image: ${DOCKER_REGISTRY-}microservicecustomeraddress
    build:
      context: .
      dockerfile: Microservice.Customer.Address.Api/Dockerfile
    ports: 
      - "13000:8080"
      - "13001:8081"
    environment: 
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: https://+:8081;http://+:8080
        ASPNETCORE_HTTPS_PORT: 8081
        JWT_ISSUER: ${JWT_ISSUER}
        JWT_AUDIENCE: ${JWT_AUDIENCE}
        JWT_SYMMETRIC_SECURITY_KEY: ${JWT_SYMMETRIC_SECURITY_KEY} 
    networks:
      - ms-order-system    
  
networks:
  ms-order-system: 
    external: true
