# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - prod-ap-ms-order-customer-address

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://prodcrmsordersystem.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fc4442b36d564e9989920e69f0bba83b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_17f46cab56bf4a5ca62638a3d2ae1c7a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: prodcrmsordersystem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fc4442b36d564e9989920e69f0bba83b }}/microservicecustomeraddress:${{ github.sha }}
        file: ./Microservice.Customer.Address.Api/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prod-ap-ms-order-customer-address'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fafc2dbe994e4440a94efcd4d41d6bf2 }}
        images: 'prodcrmsordersystem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fc4442b36d564e9989920e69f0bba83b }}/microservicecustomeraddress:${{ github.sha }}'
