# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - prod-ap-ms-order-customer-address

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://prodcrmsordersystem.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d0ce9769a0ac493a9fafe11703ee83dc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_23fc52af010741299aef927130422741 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: prodcrmsordersystem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d0ce9769a0ac493a9fafe11703ee83dc }}/microservicecustomeraddress:${{ github.sha }}
        file: ./Microservice.Customer.Address.Api/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prod-ap-ms-order-customer-address'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5032b5eaf6474f80b1031279c2f8820f }}
        images: 'prodcrmsordersystem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d0ce9769a0ac493a9fafe11703ee83dc }}/microservicecustomeraddress:${{ github.sha }}'

  unit-tests:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build Microservice.Customer.Address.Api/Microservice.Customer.Address.Api.csproj --configuration Release

      - name: Unit Tests
        run: dotnet test Microservice.Customer.Address.Api.Test.Unit/Microservice.Customer.Address.Api.Test.Unit.csproj --logger "console;verbosity=detailed"
  
  automated-api-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/PostmanCollections/MOS_Customer_Address_Api_V1_postman_collection.json" -e "${{ secrets.POSTMAN_ENVIRONMENT_ID }}" --integration-id "165236-${{ github.run_id }}"   
